version: '3'
services:
  web:
    build:
      context: ../
      args:
        PYTHON_VERSION: "${PYTHON_VERSION}"
      dockerfile: docker/app/Dockerfile
    restart: always
    environment:
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_DB_NAME
      - DJANGO_DB_USER_NAME
      - DJANGO_DB_USER_PASSWORD
      - DJANGO_DB_HOST
      - DJANGO_DB_PORT
      - DJANGO_DB_NAME_BB
      - DJANGO_DB_USER_NAME_BB
      - DJANGO_DB_USER_PASSWORD_BB
      - DJANGO_DB_HOST_BB
      - DJANGO_DB_PORT_BB
      - DJANGO_LOG_LEVEL
    command: gunicorn crossreference.wsgi:application --bind 0.0.0.0:8000 -w 6 -t 60
                      --capture-output
                      --access-logfile -
                      --log-level info
                      --reload

    volumes:
      # nginx serves the apps static files, share volume
      - static_volume:/app/src/staticfiles:Z
      - ../src/:/app/src/:Z
    container_name: crossreference-app
    network_mode: host

  nginx:
    build:
      context: ./nginx
      args:
        nginx_version: "${NGINX_VERSION}"
    restart: always
    environment:
      - NGINX_LISTENING_PORT
    volumes:
      - static_volume:/app/src/staticfiles:Z
    depends_on:
      - web
    container_name: crossreference-nginx
    network_mode: host

volumes:
  static_volume:
